name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout
      - uses: actions/checkout@master

      # Install
      - uses: snyk/actions/setup@master
      #- run: |
      #    sudo npm install -g snyk
      #    sudo npm install -g snyk-to-html
      #    snyk auth ${SNYK_TOKEN}
      #    npm install

      # Snyk Test
      - name: Run Snyk Test
        uses: snyk/actions/node@master
        with:
          args: --severity-threshold=critical

      # Snyk Monitor
      #- name: Run Snyk Monitor
      #  uses: snyk/actions/node@master
      #  with:
      #    command: monitor