name: Test Code With Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout
      - uses: actions/checkout@master

      # Install using provided Snyk action
      #- uses: snyk/actions/setup@master

      # Install directly
      - run: |
          sudo npm install -g snyk
          sudo npm install -g snyk-to-html
          snyk auth ${SNYK_TOKEN}
          npm install

      # Language-specific setup
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '16'

      # Install Project Dependencies
      #- run: npm install

      # Snyk Test with provided action
      #- name: Snyk Test
      #  uses: snyk/actions/node@master
      #  with:
      #    args: --severity-threshold=critical

      # Snyk Test directly
      - run: |
          snyk test --severity-threshold=high --json | snyk-to-html -o ./results.html
        continue-on-error: true

      - run: |
          snyk code test --severity-threshold=high
        continue-on-error: true

      - run: |
          snyk monitor  --project-tags='owner=Reed' --project-business-criticality=low --target-reference=bad_dev

      # Upload Artifact
      - name: Upload html output
        uses: actions/upload-artifact@v2
        with:
          name: results.html
          path: ./results.html

      # Snyk Monitor
      #- name: Snyk Monitor
      #  uses: snyk/actions/node@master
      #  with:
      #    command: monitor