name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout
      - uses: actions/checkout@master

      # Install and Auth
      - run: |
          sudo npm install -g snyk
          sudo npm install -g snyk-to-html
          snyk auth ${SNYK_TOKEN}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Setup Snyk actions
      - name: Snyk
        uses: snyk/actions@0.3.0

      # Snyk Test
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master

      # Snyk Monitor
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: monitor