name: "Snyk Test"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         sudo npm install -g snyk-to-html
         npm install
      continue-on-error: true
    # Run Snyk Open Source
    - name: Run Snyk Open Source
      run: |
         snyk test --severity-threshold=high --json | snyk-to-html -o ./results.html
      continue-on-error: true
   # Upload Artifact   
    - name: Upload html output
      uses: actions/upload-artifact@v2
      with:
       name: results.html
       path: ./results.html
