name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout
      - uses: actions/checkout@master

      # Install using Snyk Action:
      - uses: snyk/actions/setup@master

      # Install directly:
      #- run: |
      #    sudo npm install -g snyk
      #    sudo npm install -g snyk-to-html

      # Install Project Dependencies:
      - run: npm install --silent

      # Snyk Test
      - name: Snyk Test
        uses: snyk/actions/node@master
        with:
          args: --severity-threshold=critical

      # Snyk Monitor
      #- name: Snyk Monitor
      #  uses: snyk/actions/node@master
      #  with:
      #    command: monitor